# Generated by Django 4.1.2 on 2022-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_profile',
            field=models.ImageField(blank=True, upload_to='events/speaker_profile'),
        ),
    ]
