# Generated by Django 4.1.2 on 2022-11-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
                ('event_description', models.TextField()),
                ('speaker_name', models.CharField(max_length=50)),
                ('Perk_of_attendig_event', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('venue', models.CharField(blank=True, default='Online', max_length=50)),
                ('online_link', models.URLField(blank=True, default='https://simmifrontendtest.netlify.app', max_length=300)),
                ('time', models.DateTimeField()),
                ('image_1', models.ImageField(blank=True, upload_to='events')),
                ('image_2', models.ImageField(blank=True, upload_to='events')),
                ('image_3', models.ImageField(blank=True, upload_to='events')),
                ('duration', models.IntegerField(default=0)),
                ('attendence', models.IntegerField(default=0)),
                ('place', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
