# Generated by Django 4.1.2 on 2022-11-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_link',
            field=models.CharField(blank=True, default='None', max_length=300),
        ),
    ]
