# Generated by Django 4.1.2 on 2022-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendence',
            field=models.IntegerField(default=0),
        ),
    ]
