# Generated by Django 4.1.2 on 2022-12-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_3',
        ),
    ]
