# Generated by Django 4.1.2 on 2022-11-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_speaker_event_place_alter_event_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
