# Generated by Django 4.1.2 on 2022-11-09 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_date_alter_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='event',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 15, 36, 33, 245669)),
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
    ]
