# Generated by Django 4.1.2 on 2022-11-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_image_event_image_1_event_image_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
