# Generated by Django 4.1.2 on 2022-11-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0007_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField()),
                ('speaker_name', models.CharField(max_length=50)),
                ('Perk_of_attendig_event', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('image_1', models.ImageField(upload_to='events')),
                ('image_2', models.ImageField(blank=True, upload_to='events')),
                ('image_3', models.ImageField(blank=True, upload_to='events')),
                ('attendence', models.IntegerField(default=0)),
                ('place', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
