# Generated by Django 4.1.2 on 2022-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_using', models.IntegerField(choices=[(0, 'Card Payment'), (1, 'Internet Banking'), (2, 'UPI & E-Wallet'), (3, 'Other Payment Methods')], default=0)),
            ],
        ),
    ]
