# Generated by Django 4.1.2 on 2022-12-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Livlihood', 'Livlihood'), ('Other', 'Other'), ('HealthCare', 'HealthCare'), ('Women Empowerment', 'Women Empowerment'), ('Education', 'Education')], max_length=100),
        ),
    ]
