# Generated by Django 4.1.2 on 2022-12-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='ccv',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='amount',
            field=models.CharField(default=1, max_length=9999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='amount_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Women empowerment', 'Women empowerment')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='country',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='country_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='fname',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='num',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_details',
            name='subscription_plan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
