# Generated by Django 4.1.2 on 2022-10-18 01:31

from django.db import migrations, models
import donate.models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name=donate.models.payment_method)),
                ('card_no', models.IntegerField()),
                ('ccv', models.IntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
