# Generated by Django 4.1.2 on 2022-11-06 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0002_upi_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_form',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='donate_form',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
