# Generated by Django 4.1.2 on 2022-12-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Women empowerment', 'Women empowerment')], max_length=100),
        ),
    ]
