# Generated by Django 4.1.2 on 2022-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_remove_payment_details_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_form',
            name='phn_no',
            field=models.CharField(max_length=20),
        ),
    ]
