# Generated by Django 4.1.2 on 2022-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('Women Empowerment', 'Women Empowerment'), ('Livlihood', 'Livlihood'), ('Other', 'Other'), ('Education', 'Education')], max_length=100),
        ),
    ]
