# Generated by Django 4.1.2 on 2022-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_alter_donate_form_phn_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Give_Your_Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='donate_form',
            name='phn_no',
            field=models.CharField(max_length=12),
        ),
    ]
