# Generated by Django 4.1.2 on 2022-12-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Education', 'Education'), ('HealthCare', 'HealthCare'), ('Other', 'Other'), ('Livlihood', 'Livlihood'), ('Women Empowerment', 'Women Empowerment')], max_length=100),
        ),
    ]
