# Generated by Django 4.1.2 on 2022-10-19 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_give_your_help_alter_donate_form_phn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_form',
            name='pan_no',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='donate_form',
            name='phn_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='card_no',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='ccv',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
