# Generated by Django 4.1.2 on 2022-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Other', 'Other'), ('Education', 'Education'), ('HealthCare', 'HealthCare'), ('Women Empowerment', 'Women Empowerment'), ('Livlihood', 'Livlihood')], max_length=100),
        ),
    ]
