# Generated by Django 4.1.2 on 2022-12-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('Education', 'Education'), ('Women Empowerment', 'Women Empowerment'), ('Other', 'Other'), ('Livlihood', 'Livlihood')], max_length=100),
        ),
    ]
