# Generated by Django 4.1.2 on 2022-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('HealthCare', 'HealthCare'), ('Education', 'Education'), ('Livlihood', 'Livlihood'), ('Other', 'Other'), ('Women Empowerment', 'Women Empowerment')], max_length=100),
        ),
    ]
