# Generated by Django 4.1.2 on 2022-12-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0017_alter_payment_details_cause_for_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='cause_for_donation',
            field=models.CharField(choices=[('Women Empowerment', 'Women Empowerment'), ('Other', 'Other'), ('Education', 'Education'), ('Livlihood', 'Livlihood'), ('HealthCare', 'HealthCare')], max_length=100),
        ),
    ]
