# Generated by Django 4.1.2 on 2022-10-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('education', 'education'), ('medical camps', 'medical camps'), ('livelihood', 'livelihood'), ('women empowerment', 'women empowerment')], max_length=50)),
            ],
        ),
    ]
