# Generated by Django 4.1.2 on 2022-12-03 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('admin', models.CharField(blank=True, default='Test-Admin', max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='gallery')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Women empowerment', 'Women empowerment')], max_length=50)),
            ],
        ),
    ]
