# Generated by Django 4.1.2 on 2022-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('admin', models.CharField(default='Test Admin', max_length=50)),
                ('photo', models.ImageField(upload_to='gallery')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Women empowerment', 'Women empowerment')], max_length=50)),
            ],
        ),
    ]
