# Generated by Django 4.1.2 on 2022-10-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='education',
            new_name='Gallerytable',
        ),
    ]
