# Generated by Django 4.1.2 on 2022-12-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerytable',
            name='photo2',
            field=models.ImageField(blank=True, default=None, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='gallerytable',
            name='photo3',
            field=models.ImageField(blank=True, default=None, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallerytable',
            name='category',
            field=models.CharField(choices=[('Education', 'EDUCATION'), ('HealthCare', 'HEALTHCARE'), ('Livelihood', 'LIVELIHOOD'), ('Women Empowerment', 'WOMEN EMPOWERMENT'), ('Others', 'OTHERS')], max_length=50),
        ),
    ]
