# Generated by Django 4.1.2 on 2022-10-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_education_gallerytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerytable',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Women empowerment', 'Women empowerment')], max_length=50),
        ),
    ]
