# Generated by Django 4.1.2 on 2022-12-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerytable_photo2_gallerytable_photo3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerytable',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='gallerytable',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
