# Generated by Django 4.1.2 on 2022-11-13 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerytable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerytable',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
