# Generated by Django 4.1.2 on 2022-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerytable_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerytable',
            name='admin',
            field=models.CharField(default='Test Admin', max_length=50),
        ),
    ]
