# Generated by Django 4.1.2 on 2022-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallerytable_photo2_alter_gallerytable_photo3'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('gallery_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
        migrations.RemoveField(
            model_name='gallerytable',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gallerytable',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='gallerytable',
            name='photo3',
        ),
    ]
