# Generated by Django 4.1.2 on 2022-11-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_gallerytable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerytable',
            name='admin',
            field=models.CharField(blank=True, default='Test-Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallerytable',
            name='photo',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
