# Generated by Django 4.1.2 on 2022-11-30 17:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='welfare/blogs')),
                ('date_posted', models.DateField(default=datetime.date(2022, 11, 30))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welfare.category')),
            ],
        ),
    ]
