# Generated by Django 4.1.2 on 2022-12-04 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField(blank=True, null=True)),
                ('issue_on', models.DateField(default=datetime.date(2022, 12, 4))),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='welfare/story-of-change')),
                ('category', models.CharField(choices=[('Education', 'EDUCATION'), ('HealthCare', 'HEALTHCARE'), ('Livelihood', 'LIVELIHOOD'), ('Women Empowerment', 'WOMEN EMPOWERMENT'), ('Others', 'OTHERS')], default='Education', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 4)),
        ),
    ]
