# Generated by Django 4.1.2 on 2022-12-15 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0006_alter_blog_date_posted_alter_story_issue_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(choices=[('Education', 'EDUCATION'), ('HealthCare', 'HEALTHCARE'), ('Livelihood', 'LIVELIHOOD'), ('Women Empowerment', 'WOMEN EMPOWERMENT'), ('Others', 'OTHERS')], default='Education', max_length=20),
        ),
        migrations.AddField(
            model_name='timeline',
            name='category',
            field=models.CharField(choices=[('Education', 'EDUCATION'), ('HealthCare', 'HEALTHCARE'), ('Livelihood', 'LIVELIHOOD'), ('Women Empowerment', 'WOMEN EMPOWERMENT'), ('Others', 'OTHERS')], default='Education', max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
        migrations.AlterField(
            model_name='story',
            name='issue_on',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 15)),
        ),
    ]
