# Generated by Django 4.1.2 on 2023-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0020_alter_blog_date_posted_alter_othercause_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_by',
            field=models.CharField(default='someone', max_length=50),
        ),
    ]
