# Generated by Django 4.1.2 on 2022-11-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m',
            name='image_2',
            field=models.ImageField(default=None, upload_to='cc'),
        ),
    ]
