# Generated by Django 4.1.2 on 2022-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resp',
            name='img',
            field=models.ImageField(upload_to='about/response_and_concern/'),
        ),
    ]
