# Generated by Django 4.1.2 on 2022-11-16 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_resp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resp',
            name='num',
            field=models.CharField(max_length=10, validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
