# Generated by Django 4.1.2 on 2022-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_date',
        ),
        migrations.AddField(
            model_name='resp',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
