# Generated by Django 4.1.2 on 2022-11-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_created_date_resp_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resp',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
