# Generated by Django 4.1.2 on 2022-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Razorpay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
