# Generated by Django 4.1.2 on 2022-10-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_date_posted_alter_blog_image_and_more'),
        ('blog', '0002_alter_blog_title'),
    ]

    operations = [
    ]
