# Generated by Django 4.1.2 on 2022-11-28 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobappliedbyuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_you_heared_us', models.TextField()),
                ('jobid', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adhar_no', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)])),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('address_lane', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('job_type', models.CharField(default='Work from office', max_length=50)),
                ('admin', models.CharField(default='Test Admin', max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('immediate_supervisor', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(default='', max_length=60000)),
            ],
        ),
    ]
