# Generated by Django 4.1.2 on 2022-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='d',
            field=models.TextField(default='', max_length=60000),
        ),
    ]
