# Generated by Django 4.1.2 on 2022-11-28 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobappliedbyuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_you_heared_us', models.TextField()),
                ('jobid', models.IntegerField()),
                ('country', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('adhar_no', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('address_lane', models.TextField()),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=5)),
                ('mobile_number', models.CharField(max_length=16)),
                ('resume', models.FileField(upload_to='Jobs/Resume/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrers.jobs')),
            ],
        ),
    ]
