# Generated by Django 4.1.2 on 2022-12-19 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='skills_req',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobappliedbyuse',
            name='address_lane',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobappliedbyuse',
            name='adhar_no',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)]),
        ),
        migrations.AlterField(
            model_name='jobappliedbyuse',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobappliedbyuse',
            name='how_you_heared_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobappliedbyuse',
            name='postal_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
