# Generated by Django 4.1.2 on 2022-11-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0002_jobappliedbyuse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jobappliedbyuser',
        ),
    ]
