# Generated by Django 4.1.2 on 2022-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0002_jobs_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='d',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(default='', max_length=60000),
        ),
    ]
