# Generated by Django 4.1.2 on 2022-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrers', '0003_remove_jobs_d_alter_jobs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='admin',
            field=models.CharField(default='Test Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(default='Work from office', max_length=50),
        ),
    ]
