# Generated by Django 4.1.2 on 2022-12-23 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='aadhar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
