# Generated by Django 4.1.2 on 2022-10-19 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
