# Generated by Django 4.1.2 on 2022-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=80)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Advisory_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='about/Board Commitee Members/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_campaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Healthcare', 'Healthcare'), ('Women empowerment', 'Women empowerment')], max_length=50)),
                ('photo', models.ImageField(upload_to='about/campaigns/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Our_initiatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(choices=[('Education', 'Education'), ('Medical camps', 'Medical camps'), ('Livelihood', 'Livelihood'), ('Healthcare', 'Healthcare'), ('Women empowerment', 'Women empowerment')], max_length=50)),
                ('photo', models.ImageField(upload_to='about/initiatives/')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Senior_management_committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='about/Senior Commitee Members/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Senior_technical_committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='about/Senior tech Commitee Members/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='about/Team Members/')),
            ],
        ),
    ]
