# Generated by Django 4.1.2 on 2022-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='about/Founders/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
