# Generated by Django 4.1.2 on 2022-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonAboutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=100)),
                ('insta_id', models.URLField()),
                ('meta_id', models.URLField()),
                ('tweet_id', models.URLField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
