# Generated by Django 4.1.2 on 2022-11-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_sub_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory_board',
            name='fbid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisory_board',
            name='instaid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisory_board',
            name='tweetid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
