# Generated by Django 4.1.2 on 2022-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_delete_about_delete_advisory_board_delete_founders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonabouttable',
            name='fbid',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='commonabouttable',
            name='instaid',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='commonabouttable',
            name='tweetid',
            field=models.URLField(null=True),
        ),
    ]
