# Generated by Django 4.1.2 on 2022-11-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_advisory_board_fbid_advisory_board_instaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='senior_management_committee',
            name='fbid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senior_management_committee',
            name='instaid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senior_management_committee',
            name='tweetid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senior_technical_committee',
            name='fbid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senior_technical_committee',
            name='instaid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='senior_technical_committee',
            name='tweetid',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
