# Generated by Django 4.1.2 on 2022-12-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_commonabouttable_fbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonabouttable',
            name='position',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Co-Founder', 'Co-Founder'), ('Advisory Board Committee', 'Advisory Board Committee'), ('Senior Management Committe', 'Senior Management Committe'), ('Senior Technical Committee', 'Senior Technical Committee'), ('Executive Team', 'Executive Team')], max_length=80),
        ),
    ]
