# Generated by Django 4.1.2 on 2022-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_senior_management_committee_fbid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='founders',
            name='fbid',
            field=models.URLField(default='https://www.facebook.com/Meta/'),
        ),
        migrations.AddField(
            model_name='founders',
            name='instaid',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='founders',
            name='tweetid',
            field=models.URLField(default='https://twitter.com/'),
        ),
    ]
