# Generated by Django 4.1.2 on 2022-11-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_founders_fbid_founders_instaid_founders_tweetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory_board',
            name='fbid',
            field=models.URLField(default='https://www.facebook.com/Meta/'),
        ),
        migrations.AlterField(
            model_name='advisory_board',
            name='instaid',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='advisory_board',
            name='tweetid',
            field=models.URLField(default='https://twitter.com/'),
        ),
        migrations.AlterField(
            model_name='senior_management_committee',
            name='fbid',
            field=models.URLField(default='https://www.facebook.com/Meta/'),
        ),
        migrations.AlterField(
            model_name='senior_management_committee',
            name='instaid',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='senior_management_committee',
            name='tweetid',
            field=models.URLField(default='https://twitter.com/'),
        ),
        migrations.AlterField(
            model_name='senior_technical_committee',
            name='fbid',
            field=models.URLField(default='https://www.facebook.com/Meta/'),
        ),
        migrations.AlterField(
            model_name='senior_technical_committee',
            name='instaid',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AlterField(
            model_name='senior_technical_committee',
            name='tweetid',
            field=models.URLField(default='https://twitter.com/'),
        ),
    ]
