# Generated by Django 4.1.2 on 2022-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_commonabouttable_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonabouttable',
            name='team_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
