# Generated by Django 4.1.2 on 2022-12-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_commonabouttable_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonabouttable',
            name='team_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
