# Generated by Django 4.1.2 on 2022-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('mentor_name', models.CharField(max_length=25)),
                ('issue_date', models.DateField(auto_now=True)),
                ('img', models.ImageField(upload_to='certificates')),
                ('status', models.CharField(choices=[('Not Attended', 'Not Attended'), ('Completed', 'Completed')], max_length=15)),
            ],
        ),
    ]
