# Generated by Django 4.1.2 on 2022-12-25 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='institutial_alliance/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Coparate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=25)),
                ('patner_since', models.DateField(default=datetime.datetime.now)),
                ('profession', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='Coparate_partnership/')),
                ('desc', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('imgs', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
