# Generated by Django 4.1.2 on 2022-11-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
