# Generated by Django 4.1.2 on 2022-12-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='institutial_alliance/')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Copatner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='Coparate_partnership/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
