# Generated by Django 4.1.2 on 2022-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alliance',
            name='img',
            field=models.ImageField(default=1, upload_to='institutial_alliance/'),
            preserve_default=False,
        ),
    ]
