# Generated by Django 4.1.2 on 2022-12-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='multi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.FileField(upload_to='')),
            ],
        ),
    ]
