# Generated by Django 4.1.2 on 2022-11-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0002_alliance_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copatner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.ImageField(upload_to='Coparate_partnership/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
