# Generated by Django 4.1.2 on 2022-12-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0002_multi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='multi',
        ),
    ]
