# Generated by Django 4.1.2 on 2022-12-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0003_delete_multi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coparate',
            old_name='imgs',
            new_name='other_img',
        ),
    ]
