# Generated by Django 4.1.2 on 2022-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0004_rename_imgs_coparate_other_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coparate',
            name='other_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
