# Generated by Django 4.1.2 on 2022-12-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_aliance', '0005_alter_coparate_other_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coparate',
            name='other_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
