# Generated by Django 4.1.2 on 2022-12-03 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_from', models.CharField(max_length=100)),
                ('recognition_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('issue_on', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='awards and recognition')),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='electronic_media')),
            ],
        ),
        migrations.CreateModel(
            name='EminentPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='eminent_personality')),
                ('company_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualSupporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('reason', models.TextField()),
                ('timing', models.DateField()),
                ('message', models.TextField()),
                ('file', models.FileField(blank=True, upload_to='supporter')),
            ],
        ),
        migrations.CreateModel(
            name='PressMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='press_media')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='News Paper')),
                ('topic', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='publication')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StoryOfChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('syndrome', models.CharField(max_length=255)),
                ('how_we_helped', models.TextField()),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='story of change')),
            ],
        ),
    ]
