# Generated by Django 4.1.2 on 2022-12-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_alter_publication_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardsrecognition',
            name='image',
        ),
        migrations.RemoveField(
            model_name='electronicmedia',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='eminentpersonality',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pressmedia',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='storyofchange',
            name='image',
        ),
        migrations.AddField(
            model_name='awardsrecognition',
            name='file',
            field=models.FileField(blank=True, upload_to='awards and recognition'),
        ),
        migrations.AddField(
            model_name='electronicmedia',
            name='file',
            field=models.FileField(blank=True, upload_to='electronic_media'),
        ),
        migrations.AddField(
            model_name='eminentpersonality',
            name='file',
            field=models.FileField(blank=True, upload_to='eminent_personality'),
        ),
        migrations.AddField(
            model_name='pressmedia',
            name='file',
            field=models.FileField(blank=True, upload_to='press_media'),
        ),
        migrations.AddField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, upload_to='publication'),
        ),
        migrations.AddField(
            model_name='storyofchange',
            name='file',
            field=models.FileField(blank=True, upload_to='story of change'),
        ),
    ]
