# Generated by Django 4.1.2 on 2022-11-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0003_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressmedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='press_media'),
        ),
    ]
