# Generated by Django 4.1.2 on 2022-11-25 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0004_pressmedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eminentpersonality',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='eminentpersonality',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 25)),
        ),
        migrations.AddField(
            model_name='eminentpersonality',
            name='image',
            field=models.ImageField(blank=True, upload_to='eminent_personality'),
        ),
    ]
