# Generated by Django 4.1.2 on 2022-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0004_remove_awardsrecognition_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicmedia',
            name='file',
        ),
        migrations.AddField(
            model_name='electronicmedia',
            name='picture',
            field=models.FileField(blank=True, upload_to='electronic_media'),
        ),
    ]
