# Generated by Django 4.1.2 on 2022-11-26 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0005_eminentpersonality_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardsRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_from', models.CharField(max_length=100)),
                ('recognition_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('issue_on', models.DateField(default=datetime.date(2022, 11, 26))),
                ('image', models.ImageField(blank=True, upload_to='awards and recognition')),
            ],
        ),
        migrations.CreateModel(
            name='StoryOfChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('syndrome', models.CharField(max_length=255)),
                ('how_we_helped', models.TextField()),
                ('year', models.DateField(default=datetime.date(2022, 11, 26))),
                ('image', models.ImageField(blank=True, upload_to='story of change')),
            ],
        ),
        migrations.AlterField(
            model_name='eminentpersonality',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
    ]
