# Generated by Django 4.1.2 on 2022-11-28 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0006_awardsrecognition_storyofchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsrecognition',
            name='issue_on',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
        migrations.AlterField(
            model_name='eminentpersonality',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
        migrations.AlterField(
            model_name='storyofchange',
            name='year',
            field=models.DateField(default=datetime.date(2022, 11, 28)),
        ),
    ]
