# Generated by Django 4.1.2 on 2023-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0006_rename_picture_electronicmedia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualsupporter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='individualsupporter',
            name='phone_no',
        ),
        migrations.AlterField(
            model_name='individualsupporter',
            name='reason',
            field=models.CharField(choices=[('Healthcare', 'Healthcare'), ('Women Empowerment', 'Women Empowerment'), ('Other', 'Other'), ('Livelihood', 'Livelihood'), ('Education', 'Education')], max_length=100),
        ),
    ]
