# Generated by Django 4.1.2 on 2023-01-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0007_remove_individualsupporter_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualsupporter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='individualsupporter',
            name='timing',
        ),
        migrations.AlterField(
            model_name='individualsupporter',
            name='reason',
            field=models.CharField(choices=[('Education', 'Education'), ('Women Empowerment', 'Women Empowerment'), ('Healthcare', 'Healthcare'), ('Livelihood', 'Livelihood'), ('Other', 'Other')], max_length=100),
        ),
    ]
