# Generated by Django 4.1.2 on 2022-11-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0006_alter_eminentpersonality_date'),
        ('get_involved', '0007_alter_awardsrecognition_issue_on_and_more'),
    ]

    operations = [
    ]
