# Generated by Django 4.1.2 on 2023-01-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0008_remove_individualsupporter_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualsupporter',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualsupporter',
            name='reason',
            field=models.CharField(choices=[('Education', 'Education'), ('Healthcare', 'Healthcare'), ('Livelihood', 'Livelihood'), ('Other', 'Other'), ('Women Empowerment', 'Women Empowerment')], max_length=100),
        ),
    ]
