# Generated by Django 4.1.2 on 2022-11-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0009_alter_eminentpersonality_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsrecognition',
            name='issue_on',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 22, 9, 22, 34375)),
        ),
        migrations.AlterField(
            model_name='eminentpersonality',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 22, 9, 22, 34375)),
        ),
        migrations.AlterField(
            model_name='storyofchange',
            name='year',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 22, 9, 22, 34375)),
        ),
    ]
