# Generated by Django 4.1.2 on 2023-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0011_alter_individualsupporter_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualsupporter',
            name='reason',
            field=models.CharField(choices=[('Women Empowerment', 'Women Empowerment'), ('Healthcare', 'Healthcare'), ('Livelihood', 'Livelihood'), ('Other', 'Other'), ('Education', 'Education')], max_length=100),
        ),
    ]
