# Generated by Django 4.1.2 on 2022-11-28 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0011_alter_awardsrecognition_issue_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsrecognition',
            name='issue_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eminentpersonality',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storyofchange',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
