# Generated by Django 4.1.2 on 2023-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_involved', '0012_alter_individualsupporter_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualsupporter',
            name='reason',
            field=models.CharField(choices=[('Other', 'Other'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Livelihood', 'Livelihood'), ('Women Empowerment', 'Women Empowerment')], max_length=100),
        ),
    ]
