# Generated by Django 4.1.2 on 2022-10-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/Education')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='livelihood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/Education')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='medical_camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/Education')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='women_empowerment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='gallery/Education')),
                ('content', models.TextField()),
            ],
        ),
    ]
