# Generated by Django 4.1.2 on 2022-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSessions',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
    ]
