# Generated by Django 4.1.2 on 2022-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_certificate', '0003_donationcetificates_transactions_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationcetificates',
            name='transactions_type',
        ),
        migrations.AddField(
            model_name='donationcetificates',
            name='transactions_id',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
