# Generated by Django 4.1.2 on 2022-11-28 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generate_certificate', '0004_remove_donationcetificates_transactions_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCetificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=30)),
                ('certificate', models.FileField(upload_to='donation/subscription/certificates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
