# Generated by Django 4.1.2 on 2022-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upimages',
            name='img1',
            field=models.ImageField(upload_to='navbar/images'),
        ),
        migrations.AlterField(
            model_name='upimages',
            name='img2',
            field=models.ImageField(null=True, upload_to='navbar/images'),
        ),
        migrations.AlterField(
            model_name='upimages',
            name='img3',
            field=models.ImageField(null=True, upload_to='navbar/images'),
        ),
        migrations.AlterField(
            model_name='upimages',
            name='img4',
            field=models.ImageField(null=True, upload_to='navbar/images'),
        ),
    ]
